### PR TITLE
Make Forgot password as a linked text

### PR DESCRIPTION
**Pull request by anastasiaShpakava**

### CODE REVIEW

**Review by EvgeniyFilippov — APPROVED** [review]

**Comment by bstolyarov** [comment]
I would expect to see something like this: https://stackoverflow.com/a/69549929/4256193
using ClickableText and buildAnnotatedString

**Comment by anastasiaShpakava** [comment]
> I would expect to see something like this: https://stackoverflow.com/a/69549929/4256193 using ClickableText and buildAnnotatedString

What is the difference between what did I and this example? I mean in UI and functionality?

**Comment by bstolyarov** [comment]
> What is the difference between what did I and this example? I mean in UI and functionality?
As I understand, in your implementation text will change color after clicking on it, and change color back after the second click. But it shouldn't change color, it should just to show that text was clicked, like selector, when user clicks\focuses on the text we change the color.

**Comment by anastasiaShpakava** [comment]
> I would expect to see something like this: https://stackoverflow.com/a/69549929/4256193 using ClickableText and buildAnnotatedString

done

**Review by bstolyarov — APPROVED** [review]

**Pull request merged**
